name: "Chivesweave Mainnet Packaging"
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: Set up Erlang environment
        uses: erlef/setup-beam@v1
        with:
          otp-version: "24.3"
          rebar3-version: "3.20.0"

      - name: Install CMake and g++
        run: |
          sudo apt-get update
          sudo apt-get install cmake g++
          
      - name: rebar3 mainnet
        run: |
          ./rebar3 as mainnet tar
