name: "Chivesweave"
on:
  push:
    branches: [ "master" ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: erlang:22.0.7
    steps:
    - uses: actions/checkout@v3
    - name: Compile
      run: ./rebar3 as mainnet tar
    - name: Run tests
      run: ./bin/test

