name: "Chivesweave Mainnet Packaging"
on:
  push:
    branches: [ "master" ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: erlang:22.0.7
    steps:
    - uses: actions/checkout@v3
    - name: Install linux dependencies
      run: |
        sudo apt update
        sudo apt install libssl-dev libgmp-dev libsqlite3-dev make cmake gcc g++
    - name: Compile
      run: ./rebar3 as mainnet tar
    - name: Run tests
      run: ./bin/test

