name: "Chivesweave Mainnet Packaging"
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: erlang:22.0.7
    steps:
    - name: Clone repository
      uses: actions/checkout@v2.3.4
    - name: Install linux dependencies
      run: sudo apt-get install -y libssl-dev libgmp-dev libsqlite3-dev make cmake gcc g++
    - name: Start empd
      run: epmd -daemon
    - name: Make the mainnet package
      run: ./rebar3 as mainnet tar
    - name: Run tests
      run: ./bin/test
