name: "Chivesweave Mainnet Packaging"
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Erlang environment
        uses: erlef/setup-erlang@v1
        with:
          otp-version: 24.0  # 指定所需的 Erlang/OTP 版本

      - name: Install CMake and g++
        run: |
          sudo apt-get update
          sudo apt-get install cmake g++
