name: "Mainnet Tests"
on:
  push:
    branches: [ "master" ]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Erlang environment
        uses: erlef/setup-beam@v1
        with:
          otp-version: "24.3"
          rebar3-version: "3.20.0"

      - name: Install CMake and g++
        run: |
          sudo apt-get update
          sudo apt-get install cmake g++
          
      - name: rebar3 mainnet
        run: |
          ./rebar3 as mainnet tar

      - name: Running Test Script
        run: |
          ./bin/test
