name: "Chivesweave Tests"
on:
  push:
    branches: ["**"]
jobs:
  test:
    runs-on:
      labels: ubuntu-latest-16-cores
    steps:
      - name: Clone repository
        uses: actions/checkout@v2.3.4
        with:
          submodules: "recursive"
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "24.3"
          rebar3-version: "3.20.0"
      - name: Install linux dependencies
        run: sudo apt install libssl-dev libgmp-dev libsqlite3-dev make cmake gcc g++
      - name: Start empd
        run: epmd -daemon
      - name: Make the mainnet package
        run: |
          cd chivesweave
          ./rebar3 as mainnet tar
